#도커 (run)명령어 모음파일
#json파일과 비슷한 데이터보관용파일

#컴포즈로 띄우면, 이 컨테이너 전부 네트워크(컨테이너끼리 연결되어 포장)에 자동으로 넣어줌
services:
  #이거하면 컨테이너 띄우는듯
  #서비스 이름
  #서비스는 컨테이너를 만들기위한 정보모음(이미지, 포트, 환경변수등)
  webserver:
    image: crud:1
    build: .  #이미지 새로 업데이트하고, 컨테이너 실행
    develop:
      watch:
        - action: sync+restart  #sync->코드변경사항 컨테이너에 자동복붙 #restart -> 코드만바꿔도, 웹서버는 그대로라 반영안됨. 컨테이너(웹서버 포함)도 리스타트 하라는뜻
          path: .       #intellij 경로
          target: /app  #컨테이너 안 경로임
    ports: #포트바인딩
      - 8100:8100
    depends_on: #db컨테이너에 의존(올바른 실행순서를위해)
      - db
    networks:
      - mynet1
      - mynet2

  nginx:
    image: nginx:1
    ports: #포트바인딩
      - 80:80
    networks:
      - mynet1
    restart: always   #현 컨테이너가 다운되면 항상 재시작하게.

  db:
    image: postgres:16.10-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwer1234
    networks:
      - mynet2
    volumes:
      - test_vol:/var/lib/postgresql/data

volumes:
  test_vol:
    external: true

networks:
  mynet1:
  mynet2: